CREATE DATABASE ESCOLA;
USE ESCOLA;

CREATE TABLE ALUNES (
	ID BIGINT AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    RG VARCHAR(30) NOT NULL,
    TURMA VARCHAR(30) NOT NULL,
    NOTA INT,
    PRIMARY KEY(ID)
);

INSERT INTO ALUNES (NOME, RG, TURMA, NOTA) VALUES ("Rodrigo","00.000.000-0","A",3);
INSERT INTO ALUNES (NOME, RG, TURMA, NOTA) VALUES ("Roseo","00.000.000-0","A",4);
INSERT INTO ALUNES (NOME, RG, TURMA, NOTA) VALUES ("Lopes","00.000.000-0","A",5);
INSERT INTO ALUNES (NOME, RG, TURMA, NOTA) VALUES ("Da","00.000.000-0","A",6);
INSERT INTO ALUNES (NOME, RG, TURMA, NOTA) VALUES ("Costa","00.000.000-0","A",7);
INSERT INTO ALUNES (NOME, RG, TURMA, NOTA) VALUES ("Nick","00.000.000-0","B",8);
INSERT INTO ALUNES (NOME, RG, TURMA, NOTA) VALUES ("NoLOL","00.000.000-0","B",9);
INSERT INTO ALUNES (NOME, RG, TURMA, NOTA) VALUES ("TraficanteDMiojo","00.000.000-0","C",10);

SELECT * FROM ALUNES WHERE NOTA > 7;
SELECT * FROM ALUNES WHERE NOTA < 7;

UPDATE ALUNES SET NOTA = 0 WHERE ID = 8;