CREATE DATABASE ECOMMERCE;
USE ECOMMERCE;

CREATE TABLE PRODUTOS (
	ID BIGINT AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    MARCA VARCHAR(30),
    ESTOQUE INT,
    VALOR DECIMAL(10,2),
    PRIMARY KEY(ID)
);

INSERT INTO PRODUTOS (NOME, MARCA, ESTOQUE, VALOR) VALUES ("Camisa Florida","CamisasBrasil",10,100);
INSERT INTO PRODUTOS (NOME, MARCA, ESTOQUE, VALOR) VALUES ("Calça Jeans","CalçasSA",7,200);
INSERT INTO PRODUTOS (NOME, MARCA, ESTOQUE, VALOR) VALUES ("Sapato Preto","SapatosTop",12,300);
INSERT INTO PRODUTOS (NOME, MARCA, ESTOQUE, VALOR) VALUES ("Tênis Branco","Nike",4,400);
INSERT INTO PRODUTOS (NOME, MARCA, ESTOQUE, VALOR) VALUES ("Boné Neon","TapaPote",3,500);
INSERT INTO PRODUTOS (NOME, MARCA, ESTOQUE, VALOR) VALUES ("Jaqueta de Couro","Êra",2,600);
INSERT INTO PRODUTOS (NOME, MARCA, ESTOQUE, VALOR) VALUES ("Papete do Seninha","Sei lá",8,700);
INSERT INTO PRODUTOS (NOME, MARCA, ESTOQUE, VALOR) VALUES ("Calça Custom","Eu mesmo que fiz :D",1,800);

SELECT * FROM PRODUTOS WHERE VALOR > 500;
SELECT * FROM PRODUTOS WHERE VALOR < 500;

UPDATE PRODUTOS SET ESTOQUE = 0 WHERE ID = 8;