CREATE DATABASE RH;
USE RH;

CREATE TABLE FUNCIONARIES (
	ID BIGINT AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    CPF VARCHAR(30) NOT NULL,
    SALARIO DECIMAL(10,2),
    DATA_NASCIMENTO DATE,
    PRIMARY KEY(ID)
);

INSERT INTO FUNCIONARIES (NOME, CPF, SALARIO) VALUES ("Rodrigo","XXX.XXX.XXX-XX",1000);
INSERT INTO FUNCIONARIES (NOME, CPF, SALARIO) VALUES ("Roseo","XXX.XXX.XXX-XX",1500);
INSERT INTO FUNCIONARIES (NOME, CPF, SALARIO) VALUES ("Lopes","XXX.XXX.XXX-XX",2000);
INSERT INTO FUNCIONARIES (NOME, CPF, SALARIO) VALUES ("Da","XXX.XXX.XXX-XX",2500);
INSERT INTO FUNCIONARIES (NOME, CPF, SALARIO) VALUES ("Costa","XXX.XXX.XXX-XX",3000);

SELECT * FROM FUNCIONARIES WHERE SALARIO > 2000;
SELECT * FROM FUNCIONARIES WHERE SALARIO < 2000;

UPDATE FUNCIONARIES SET CPF = "123.456.789-10" WHERE ID = 2;