CREATE TABLE `TB_TEMA` (
	`ID` bigint NOT NULL AUTO_INCREMENT,
	`TIPO` varchar(100) NOT NULL,
	`ACESSO` int(11) NOT NULL,
	`STATUS` BOOLEAN NOT NULL,
	`DESCRICAO` varchar(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `TB_POSTAGEM` (
	`ID` bigint NOT NULL AUTO_INCREMENT,
	`TITULO` varchar(255) NOT NULL,
	`CONTEUDO` varchar(280) NOT NULL,
	`DATA` DATETIME,
	`ENDERECO` varchar(255),
	`ID_USUARIO` bigint NOT NULL,
	`ID_TEMA` bigint NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `TB_USUARIO` (
	`ID` bigint NOT NULL AUTO_INCREMENT,
	`NOME` varchar(255) NOT NULL AUTO_INCREMENT,
	`EMAIL` varchar(255) NOT NULL AUTO_INCREMENT,
	`SENHA` varchar(255) NOT NULL AUTO_INCREMENT,
	`ACESSO` int(11) NOT NULL,
	PRIMARY KEY (`ID`)
);

ALTER TABLE `TB_POSTAGEM` ADD CONSTRAINT `TB_POSTAGEM_fk0` FOREIGN KEY (`ID_USUARIO`) REFERENCES `TB_USUARIO`(`ID`);

ALTER TABLE `TB_POSTAGEM` ADD CONSTRAINT `TB_POSTAGEM_fk1` FOREIGN KEY (`ID_TEMA`) REFERENCES `TB_TEMA`(`ID`);




