CREATE DATABASE DB_FARMACIA_DO_BEM;
USE DB_FARMACIA_DO_BEM;

CREATE TABLE TB_CATEGORIA(
	ID INT(11) AUTO_INCREMENT, PRIMARY KEY(ID),
    NOME VARCHAR(30) NOT NULL,
    TARJA VARCHAR(30)
) ENGINE=INNODB;

CREATE TABLE TB_PRODUTO(
	ID INT(11) AUTO_INCREMENT, PRIMARY KEY(ID),
    NOME VARCHAR(30) NOT NULL,
    FABRICANTE VARCHAR(30),
    VALOR DECIMAL(8,2) NOT NULL,
    CATEGORIA INT NOT NULL REFERENCES TB_CATEGORIA(ID)
) ENGINE=INNODB;

INSERT INTO TB_CATEGORIA(NOME) VALUES
("Relaxante muscular"),
("Anti-inflamatório"),
("Calmante"),
("Estômago"),
("Anti-alérgico");

INSERT INTO TB_PRODUTO(NOME,VALOR,CATEGORIA) VALUES
("Fica frio ai",1,1),
("Tranquileba",3,3),
("Sem dor",10,2),
("Buchin chei",30,4),
("Atchin",40,5),
("Opa",50,1),
("Ops",30,5),
("Eita",70,3);

SELECT * FROM TB_PRODUTO WHERE VALOR > 50;

SELECT * FROM TB_PRODUTO WHERE VALOR >= 3 AND VALOR <= 60;

SELECT * FROM TB_PRODUTO WHERE NOME LIKE "%B%";

SELECT TB_PRODUTO.NOME, TB_PRODUTO.VALOR, TB_CATEGORIA.NOME
FROM TB_PRODUTO
INNER JOIN TB_CATEGORIA ON TB_CATEGORIA.ID = TB_PRODUTO.CATEGORIA;

SELECT TB_PRODUTO.NOME, TB_PRODUTO.VALOR, TB_CATEGORIA.NOME
FROM TB_PRODUTO
INNER JOIN TB_CATEGORIA ON TB_CATEGORIA.ID = TB_PRODUTO.CATEGORIA
WHERE TB_CATEGORIA.NOME = "Calmante";