CREATE DATABASE DB_GENERATION_GAME_ONLINE;
USE DB_GENERATION_GAME_ONLINE;

CREATE TABLE TB_CLASSE(
	ID INT(11) AUTO_INCREMENT, PRIMARY KEY(ID),
    NOME VARCHAR(30) NOT NULL,
    TRANSCLASSE VARCHAR(30)
) ENGINE=INNODB;

CREATE TABLE TB_PERSONAGEM(
	ID BIGINT AUTO_INCREMENT, PRIMARY KEY(ID),
    NOME VARCHAR(30) NOT NULL,
    DEFESA INT NOT NULL,
    ATAQUE INT NOT NULL,
    CLASSE INT NOT NULL REFERENCES TB_CLASSE(ID)
) ENGINE=INNODB;

INSERT INTO TB_CLASSE(NOME,TRANSCLASSE) VALUES
("Arqueiro","Caçador"),
("Cavaleiro","Lorde"),
("Mago","Arquimago"),
("Gatuno","Merrcenario"),
("Noviço","Sacerdote");

INSERT INTO TB_PERSONAGEM(NOME,DEFESA,ATAQUE,CLASSE) VALUES
("Rodrigo",500,1000,1),
("Roseo",1000,2200,2),
("Lopes",2000,3100,3),
("Da",3000,4500,4),
("Costa",4000,5700,5),
("Miojo",5000,6000,5),
("TraficanteDMiojo",7000,8900,4),
("Legolas",700,1500,1);

SELECT * FROM TB_PERSONAGEM WHERE ATAQUE > 2000;

SELECT * FROM TB_PERSONAGEM
WHERE DEFESA >= 1000 AND DEFESA <= 2000;

SELECT * FROM TB_PERSONAGEM WHERE NOME LIKE "%c%";

SELECT TB_PERSONAGEM.NOME,TB_PERSONAGEM.DEFESA,TB_PERSONAGEM.ATAQUE,TB_CLASSE.NOME
FROM TB_PERSONAGEM
INNER JOIN TB_CLASSE ON TB_CLASSE.ID = TB_PERSONAGEM.CLASSE;

SELECT TB_PERSONAGEM.NOME,TB_PERSONAGEM.DEFESA,TB_PERSONAGEM.ATAQUE,TB_CLASSE.NOME
FROM TB_PERSONAGEM
INNER JOIN TB_CLASSE ON TB_CLASSE.ID = TB_PERSONAGEM.CLASSE
WHERE TB_CLASSE.NOME = "ARQUEIRO";